version: '3.8'

services:
  db:
    image: postgres:17
    container_name: basededatos
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gamefinder
    ports:
      - '5432:5432'
    volumes:
      - ./psql_data:/var/lib/postgresql/data
